### PR TITLE
S2_week3作業

### PR DESCRIPTION
**Pull request by peihsuan1225**
周姵萱
http://52.9.113.1:8000/
http://52.9.113.1:8000/attraction/10

麻煩老師謝謝~

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Extend layout to full width in mobile layout.
52 9 113 1_8000_attraction_10

**Comment by peihsuan1225** [comment]
我修改好了再麻煩老師~

周姵萱
http://52.9.113.1:8000/
http://52.9.113.1:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
52 9 113 1_8000_attraction_10

**Comment by peihsuan1225** [comment]
修改好了再麻煩老師~

周姵萱
http://52.9.113.1:8000/
http://52.9.113.1:8000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
