### PR TITLE
S2_week2作業

### PR DESCRIPTION
**Pull request by peihsuan1225**
周姵萱
http://52.9.113.1:8000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Text size of 預定行程、登入註冊 should align with design.

**Comment by peihsuan1225** [comment]
老師眼睛好利~
我修改好了再麻煩老師~

周姵萱
http://52.9.113.1:8000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by peihsuan1225** [comment]
謝謝

**Pull request merged**
