### PR TITLE
S2_week5作業

### PR DESCRIPTION
**Pull request by peihsuan1225**
周姵萱
http://52.9.113.1:8000/
http://52.9.113.1:8000/attraction/10
http://52.9.113.1:8000/booking

交作業，麻煩老師~

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your booking page calls User Auth API 2 times. 1 time API call is enough to meet requirements.

**Comment by peihsuan1225** [comment]
周姵萱
http://52.9.113.1:8000/
http://52.9.113.1:8000/attraction/10
http://52.9.113.1:8000/booking

修改好了 再麻煩老師

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by peihsuan1225** [comment]
謝謝~

**Pull request merged**
